//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentHouseRentals.DALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualTransactionDetail
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionOutDate { get; set; }
        public Nullable<System.DateTime> TransactionInDate { get; set; }
        public int CustomerID { get; set; }
        public string Type { get; set; }
        public int Quantity { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
