//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentHouseRentals.DALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransactionsDetail
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int QuantityPresent { get; set; }
        public Nullable<int> QuantityBooked { get; set; }
        public int TransactionID { get; set; }
        public int ProductID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public int Quantity { get; set; }
    }
}
