//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string userEmail { get; set; }
        public string userName { get; set; }
        public int userPhone { get; set; }
        public int userRoleID { get; set; }
        public int userCountryID { get; set; }
        public int userStateID { get; set; }
        public int userCityID { get; set; }
        public string userGender { get; set; }
        public System.DateTime userDateOfBirth { get; set; }
        public string userBloodGroup { get; set; }
    
        public virtual City City { get; set; }
        public virtual country country { get; set; }
        public virtual State State { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserCredential UserCredential { get; set; }
    }
}
