//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files_Storage
    {
        public int userid { get; set; }
        public int fileid { get; set; }
        public string ActualfileName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string StoredFileName { get; set; }
    }
}
