//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userEmail { get; set; }
        public int userPhone { get; set; }
        public int userPresentCountryID { get; set; }
        public int userPresentStateID { get; set; }
        public string userGender { get; set; }
        public System.DateTime userDateOfBirth { get; set; }
        public string userPresentLine1 { get; set; }
        public string userPresentLine2 { get; set; }
        public int userPresentPincode { get; set; }
        public int userPermanentPincode { get; set; }
        public string userPermanentLine1 { get; set; }
        public string userPermanentLine2 { get; set; }
        public string userPresentCity { get; set; }
        public string userPermanentCity { get; set; }
        public string userHobbies { get; set; }
        public string userSubscribed { get; set; }
        public int userPermanentCountryID { get; set; }
        public int userPermanentStateID { get; set; }
        public string imagename { get; set; }
        public byte[] imagedata { get; set; }
        public string userpassword { get; set; }
    
        public virtual country country { get; set; }
        public virtual State State { get; set; }
    }
}
